[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'openssl']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm install', 'npx prisma generate', 'npx prisma db push']

[start]
cmd = 'npm start'