[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "mysteryverse-backend"
source = "./backend"

[services.variables]
PORT = "3333"
NODE_ENV = "production"