name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mystery-verse/frontend/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd mystery-verse/frontend
        npm ci

    - name: Build frontend
      run: |
        cd mystery-verse/frontend
        npm run build
      env:
        VITE_API_URL: https://mysteryverse-backend.onrender.com

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mystery-verse/frontend/dist